name: switchml-pytorch

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - cffi 
  - cmake 
  - cudatoolkit-dev=10.1
  - cudnn=7.6
  - magma-cuda101
  - mkl 
  - mkl-include
  - mpi4py
  - ninja
  - numpy
  - openmpi
  - python=3.7
  - pyyaml
  - setuptools 
  
